<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Team::insert([
            ['name' => 'Bayern Munich', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Bayer Leverkusen', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Borussia Dortmund', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'RB Leipzig', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Stuttgart', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Friburgo', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Eintracht Frankfurt', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Union Berlin', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Heidenheim', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Mainz', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Werder Bremen', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Augsburgo', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Wolfsburgo', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => "Borussia M'gladbach", 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Hoffenheim', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Bochum', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'St. Pauli', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Kiel', 'country_id' => 82, 'created_at' => Carbon::now()],
            ['name' => 'Aston Villa', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Liverpool', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Arsenal', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Manchester City', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Chelsea', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Newcastle', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Brighton', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Nottingham Forest', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Fulham', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Tottenham', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Manchester United', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Brentford', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Bournemouth', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'West Ham', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Leicester', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Crystal Palace', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Ipswich', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Southampton', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Everton', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Wolves', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Real Madrid', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Atlético de Madrid', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Barcelona', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Girona', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Athletic Club', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Villareal', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Alavés', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Osasuna', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Celta de Vigo', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Rayo Vallecano', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Real Betis', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Mallorca', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Espanyol', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Leganés', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Sevilla', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Real Sociedad', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Real Valladolid', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Getafe', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Valencia', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Las Palmas', 'country_id' => 207, 'created_at' => Carbon::now()],
            ['name' => 'Juventus', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Bolonia', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Inter', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Atalanta', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'AC Milan', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Torino', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Nápoles', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Udinese', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Empoli', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Lazio', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Roma', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Verona', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Fiorentina', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Parma', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Genoa', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Lecce', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Venezia', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Monza', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Como', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Cagliari', 'country_id' => 107, 'created_at' => Carbon::now()],
            ['name' => 'Mónaco', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Brest', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'PSG', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Lille', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Marsella', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Lens', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Nantes', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Reims', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Niza', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Stade Rennais', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Estrasburgo', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Le Havre', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Toulouse', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Lyon', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Montpellier', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Auxerre', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Saint-Étienne', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'Angers', 'country_id' => 75, 'created_at' => Carbon::now()],
            ['name' => 'PSV', 'country_id' => 156, 'created_at' => Carbon::now()],
            ['name' => 'Feyenoord', 'country_id' => 156, 'created_at' => Carbon::now()],
            ['name' => 'Twente', 'country_id' => 156, 'created_at' => Carbon::now()],
            ['name' => 'AZ Alkmaar', 'country_id' => 156, 'created_at' => Carbon::now()],
            ['name' => 'Ajax', 'country_id' => 156, 'created_at' => Carbon::now()],
            ['name' => 'Sturm Graz', 'country_id' => 15, 'created_at' => Carbon::now()],
            ['name' => 'Salzburgo', 'country_id' => 15, 'created_at' => Carbon::now()],
            ['name' => 'Sporting CP', 'country_id' => 177, 'created_at' => Carbon::now()],
            ['name' => 'Benfica', 'country_id' => 177, 'created_at' => Carbon::now()],
            ['name' => 'Oporto', 'country_id' => 177, 'created_at' => Carbon::now()],
            ['name' => 'SC Braga', 'country_id' => 177, 'created_at' => Carbon::now()],
            ['name' => 'Estrella Roja', 'country_id' => 196, 'created_at' => Carbon::now()],
            ['name' => 'Sparta Praga', 'country_id' => 58, 'created_at' => Carbon::now()],
            ['name' => 'Slavia Praga', 'country_id' => 58, 'created_at' => Carbon::now()],
            ['name' => 'Plzen', 'country_id' => 58, 'created_at' => Carbon::now()],
            ['name' => 'Shakhtar', 'country_id' => 230, 'created_at' => Carbon::now()],
            ['name' => 'Dinamo Kiev', 'country_id' => 230, 'created_at' => Carbon::now()],
            ['name' => 'Club Brujas', 'country_id' => 22, 'created_at' => Carbon::now()],
            ['name' => 'Anderlecht', 'country_id' => 22, 'created_at' => Carbon::now()],
            ['name' => 'Royale Union SG', 'country_id' => 22, 'created_at' => Carbon::now()],
            ['name' => 'Young Boys', 'country_id' => 214, 'created_at' => Carbon::now()],
            ['name' => 'Slovan Bratislava', 'country_id' => 200, 'created_at' => Carbon::now()],
            ['name' => 'Dinamo Zagreb', 'country_id' => 55, 'created_at' => Carbon::now()],
            ['name' => 'Celtic', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Rangers', 'country_id' => 232, 'created_at' => Carbon::now()],
            ['name' => 'Ferencvaros', 'country_id' => 99, 'created_at' => Carbon::now()],
            ['name' => 'Galatasaray', 'country_id' => 225, 'created_at' => Carbon::now()],
            ['name' => 'Fenerbahçe', 'country_id' => 225, 'created_at' => Carbon::now()],
            ['name' => 'Besiktas', 'country_id' => 225, 'created_at' => Carbon::now()],
            ['name' => 'PAOK', 'country_id' => 85, 'created_at' => Carbon::now()],
            ['name' => 'Olympiacos', 'country_id' => 85, 'created_at' => Carbon::now()],
            ['name' => 'Ludogorets', 'country_id' => 34, 'created_at' => Carbon::now()],
            ['name' => 'Midtjylland', 'country_id' => 59, 'created_at' => Carbon::now()],
            ['name' => 'Bodo/Glimt', 'country_id' => 165, 'created_at' => Carbon::now()],
            ['name' => 'Elfsborg', 'country_id' => 213, 'created_at' => Carbon::now()],
            ['name' => 'Malmö', 'country_id' => 213, 'created_at' => Carbon::now()],
            ['name' => 'FCSB', 'country_id' => 181, 'created_at' => Carbon::now()],
            ['name' => 'RFS Riga', 'country_id' => 69, 'created_at' => Carbon::now()],
            ['name' => 'Maccabi Tel Aviv', 'country_id' => 106, 'created_at' => Carbon::now()],
            ['name' => 'Qarabag', 'country_id' => 16, 'created_at' => Carbon::now()],

        ]);
    }
}
